# Generated by Django 4.0.3 on 2023-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0004_alter_machine_unique_together_alter_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='machine',
            unique_together={('location', 'seri_numer')},
        ),
    ]
