# Generated by Django 4.0.3 on 2023-03-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmsApp', '0005_alter_machine_name_alter_machine_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
