# Generated by Django 4.0.3 on 2023-04-06 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fmsApp', '0006_alter_post_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'unique_together': {('grade', 'manufacturer')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='material',
            field=models.ManyToManyField(blank=True, null=True, to='fmsApp.material'),
        ),
    ]
